DROP TABLE IF EXISTS thfsupport.tickets;

CREATE TABLE IF NOT EXISTS thfsupport.tickets(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
timeCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
termID VARCHAR(20),
issue VARCHAR(200),
notes LONGTEXT,
calledBy INT,
closedBy INT,
ticketStatus INT,
timeClosed TIMESTAMP
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;